version: "3"
services:
  app:
    container_name: december-app
    image: december-app-image
    restart: always
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /mongodb_data:/data/db
    ports:
      - '27017:27017'

